### ISSUE TITLE
Container/Presentational Pattern

### ISSUE THREAD

**Issue by baristunar** [baristunar/patterns-dev-tr#2]
Container/Presentational Pattern should be translated into Turkish.

Source: [patterns.dev](https://www.patterns.dev/posts/presentational-container-pattern/)

**Comment by aycanogut** [comment]
Bu çeviriyi yaptım, uygum zamanda PR açacağım.

**Comment by aycanogut** [comment]
Bu çeviri için bir PR açtım.
